name: Add-on Examples

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Release ]
        platform: [ Win32, x64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build
        run: msbuild './reshade/examples/Examples.sln' /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: examples-${{ matrix.configuration }}-${{ matrix.platform }}
          path: './reshade/bin/${{ matrix.platform }}/${{ matrix.configuration }} Examples/*.addon*'
